version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "debsnilsamudra"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: blog_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes: 
      - app_data:/var/lib/app
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False" # Disables authentication
    ports:
    - "5050:80"
    depends_on:
    - db
    volumes:
    - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  app_data:
  pgadmin_data:
